### ISSUE TITLE
Microsite setup

### ISSUE THREAD

**Issue by JesusMtnez** [JesusMtnez/homelab#10]
## Description

Add basic microsite setup to expose documentation for the homelab under a website. Options are:

- https://jesusmtnez.es/homelab
- https://homelab.jesusmtnez.es

## Tasks

- [ ] Find documentation tool 
  - [MkDocs](https://www.mkdocs.org/) + [MkDocs material](https://squidfunk.github.io/mkdocs-material/)
  - [Zola](https://www.getzola.org/) + [Adidoks](https://adidoks.org/)
  - [Hugo](https://gohugo.io/) + [Doks](https://getdoks.org/)
- [ ] Add `tasks` to handle microsite
- [ ] Publish microsite using GitHub Actions

**Comment by JesusMtnez** [comment]
Closed by #316
