### ISSUE TITLE
Add PostgreSQL instance

### ISSUE THREAD

**Issue by JesusMtnez** [JesusMtnez/homelab#198]
## Tasks

- [ ] Provision PostgreSQL instance using ansible
- [ ] Configure user / databases
- [ ] Set up backup strategy

## Links

- https://galaxy.ansible.com/community/postgresql
