### ISSUE TITLE
Add k8s linting

### ISSUE THREAD

**Issue by JesusMtnez** [JesusMtnez/homelab#8]
## Description

Integrate a linter for all k8s yml files, to at least validate some formatting and style.

## Tasks

- [ ] Find linter tool (is it under `nixpkgs`)?
- [ ] Add `task` to format all k8s files
- [ ] Add `task` to lint all k8s files
- [ ] Integrate lint task in a GitHub Actions job
