### ISSUE TITLE
Add ansible linting

### ISSUE THREAD

**Issue by JesusMtnez** [JesusMtnez/homelab#9]
## Description

Integrate a linter for all ansible yml files, to at least validate some formatting and style.

## Tasks

- [x] Find linter tool (is it under `nixpkgs`)?
- [x] Add `task` to format all ansible files
- [x] Add `task` to lint all ansible files
- [x] Integrate lint task in a GitHub Actions job

**Comment by JesusMtnez** [comment]
- `ansible-lint` restored: 6ec91d2d4eb5a54bc19c720a7aeddef659f17448

**Comment by JesusMtnez** [comment]
- apply linter suggestions and improvements: 18bc3d8cdc2e5df5905e938227cb8d8bf06b52a0

**Comment by JesusMtnez** [comment]
- add task to lint ansible files: 006657a5cecd8abe4e81a1be33aa074cf368b513

**Comment by JesusMtnez** [comment]
Close by: 59b46ecc72f4d31353a9f65868c996abc1b073c2
